services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: teler-ultravox:latest
    container_name: ultravox_app
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    ports:
      - "4040:4040"
    env_file: ".env"
    command: http app:8000
    restart: unless-stopped
    depends_on:
      - app

networks:
  default:
    name: teler-ultravox-bridge
